Additional registers and fields for USB host support
rp-rs/rp2040-pac pull request #85
Opened 2023-08-04 08:42 UTC by nilclass

Related to https://github.com/rp-rs/rp-hal/pull/660

2023-08-04 13:48 UTC, ithinuel reviewed
Does the `HOST_POLL_INTERVAL` field also apply to epx_control ?

It doesn't seem to be added. If that's expected, I'm happy with the PR.

2023-08-04 14:22 UTC, nilclass commented
> Does the `HOST_POLL_INTERVAL` field also apply to epx_control ?
>
> It doesn't seem to be added. If that's expected, I'm happy with the PR.

It's not needed for epx_control. Technically it's also not needed for the "EP*_OUT_CONTROL" registers (which are unused in host mode), but the IN and OUT variants must have the same fields to be turned into an array.

2023-08-04 15:39 UTC, ithinuel approved these changes
LGTM

2023-08-06 10:01 UTC, nilclass commented
I've added one more change just now, regarding `ADDR_ENDP1-15` (description updated above).

2023-08-06 15:23 UTC, ithinuel requested changes
I left as suggestion to enhance readability of the yaml file (and avoid error prone repetitions).
A similar use of [name matching](https://github.com/stm32-rs/svdtools#name-matching) is done for spinlocks.

2023-08-06 15:23 UTC, ithinuel commented on svd/rp2040.yaml
> +      name: "HOST_ADDR_ENDP%s"
```suggestion
  # The ADDR_ENDP* registers are first collected into the array HOST_ADDR_ENDP.
  # This renaming is necessary to avoid collision with the "ADDR_ENDP" register used in device mode.
  _array:
    "ADDR_ENDP[0123456789],ADDR_ENDP1[012345]":
      name: "HOST_ADDR_ENDP%s"
      description: "Interrupt endpoints. Only valid in HOST mode."
```

2023-08-06 15:57 UTC, nilclass commented
> I left as suggestion to enhance readability of the yaml file (and avoid error prone repetitions).

Nice, applied, that's much better!

2023-08-06 20:37 UTC, ithinuel approved these changes

2023-08-07 20:57 UTC, merged