Add VSEL_A, enum for setting on-chip voltage regulator voltage
rp-rs/rp2040-pac pull request #89
Opened 2024-01-19 08:33 UTC by AkiyukiOkayasu

The increase in core voltage is mainly used for overclocking.
At first I sent a PR https://github.com/rp-rs/rp-hal/pull/757 to rp-hal, but on @ithinuel's advice I decided to contribute to the PAC first.  

This allows the voltage to be set in this way.  
`pac.VREG_AND_CHIP_RESET.write(|w| w.vsel.variant(VSEL_A::VOLTAGE1_20));`

Previously, unsafe was required :(
`pac.VREG_AND_CHIP_RESET.write(|w| unsafe { w.vsel().bits(12u8) });`

2024-01-19 08:50 UTC, 9names requested changes

2024-01-19 08:50 UTC, 9names commented on src/vreg_and_chip_reset/vreg.rs
> +    #[doc = "6: 0.85V"]
Missing a setting for 0.80V here
```suggestion
    #[doc = "5: 0.80V"]
    VOLTAGE0_80 = 5
    #[doc = "6: 0.85V"]
```

2024-01-19 13:11 UTC, AkiyukiOkayasu commented on src/vreg_and_chip_reset/vreg.rs
> +    #[doc = "6: 0.85V"]
Thank you, I just added it.

2024-01-19 17:10 UTC, ithinuel approved these changes
LGTM

2024-01-20 03:11 UTC, 9names approved these changes

2024-01-20 05:59 UTC, merged